# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#read csv
results = pd.read_csv("../WeatherPy/citiesdata.csv")
results

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Narsaq,60.92,-46.05,57.20,71,75,5.82,GL,1594492678
1,1,Vaini,-21.20,-175.20,71.60,83,75,10.29,TO,1594492638
2,2,Mataura,-46.19,168.86,44.71,93,100,4.59,NZ,1594492679
3,3,Marshfield,44.67,-90.17,82.40,51,40,12.75,US,1594492570
4,4,Macheng,31.18,115.03,78.30,90,100,3.91,CN,1594492680
...,...,...,...,...,...,...,...,...,...,...
557,557,Distrikt Brokopondo,4.75,-55.17,87.10,61,0,7.99,SR,1594493029
558,558,Erenhot,43.65,111.98,73.96,52,100,13.58,CN,1594492957
559,559,Boguchany,58.38,97.45,53.58,80,76,3.56,RU,1594493031
560,560,Turukhansk,65.82,87.98,51.26,91,69,6.71,RU,1594493031
561,561,Ocotal,13.63,-86.48,84.36,50,95,8.23,NI,1594493031

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#generating heatmap
h_map = gmaps.figure()

#locations
l = results[["Lat","Lng"]]

#weight
humidity = results["Humidity"]
layer = gmaps.heatmap_layer(l, weights = humidity, dissipating = False, point_radius = 3, max_intensity = humidity.max())

#add heat layer
h_map.add_layer(layer)
h_map

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
#checking conditionals
weatherConditions = results.loc[(results["Max Temp"] < 80) & 
                                (results["Max Temp"] > 70) & 
                                (results["Wind Speed"] < 10) & 
                                (results["Cloudiness"] == 0), :]

#drop rows that contain missing values
weatherConditions.dropna()
weatherConditions.reset_index(inplace = True)
weatherConditions

,index,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,6,6,AcarÃ­,-15.43,-74.62,72.66,38,0,8.08,PE,1594492681
1,24,24,Pidhorodne,48.58,35.11,71.60,53,0,6.71,UA,1594492690
2,28,28,Caravelas,-17.71,-39.25,76.05,70,0,5.91,BR,1594492692
3,161,161,Antsohihy,-14.88,47.99,70.32,73,0,4.41,MG,1594492758
4,180,180,Vila Velha,-20.33,-40.29,78.01,61,0,9.17,BR,1594492567
5,209,209,Shaunavon,49.65,-108.42,75.22,36,0,6.80,CA,1594492783
6,250,250,Oruzgan,32.83,66.00,70.05,28,0,5.84,AF,1594492804
7,251,251,BeyÅŸehir,37.68,31.72,70.02,39,0,4.83,TR,1594492804
8,328,328,Arrondissement d'Ajaccio,42.00,8.92,77.00,78,0,5.82,FR,1594492915
9,356,356,Angoche,-16.23,39.91,72.90,75,0,7.54,MZ,1594492929
10,407,407,AlpinÃ³polis,-20.86,-46.39,74.95,44,0,5.59,BR,1594492957
11,474,474,Uglovoye,44.82,33.60,71.31,61,0,8.03,UA,1594492989
12,493,493,Vallenar,-28.57,-70.76,75.88,22,0,6.22,CL,1594492999
13,503,503,Atbasar,51.80,68.33,72.28,75,0,4.68,KZ,1594492857
14,525,525,Mirabela,-16.26,-44.16,79.09,31,0,7.34,BR,1594493014
15,549,549,Payo,-3.75,103.64,71.80,95,0,2.04,ID,1594493025
16,553,553,Kamina,-8.74,24.99,70.93,46,0,2.71,CD,1594493027

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [12]:
#specific url
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

#generate empty df
hotel_df = []

#traverse from 0 to last index of weatherConditions list
for x in range(len(weatherConditions)):
    
    lat = weatherConditions.loc[x]["Lat"]
    lng = weatherConditions.loc[x]["Lng"]
    
    #setting parameters
    param = {"types" : "hotel", "radius":5000, "location": f"{lat},{lng}","key": g_key}

    
    response_json = requests.get(url , params = param).json()
    try:
        hotel_df.append(response_json["results"][0]["name"])
    except:
        hotel_df.append("NA")

#adding hotel column to dataframe
weatherConditions["Hotel Name"] = hotel_df
#weatherConditions.dropna(how="any")
weatherConditions

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,index,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,6,6,AcarÃ­,-15.43,-74.62,72.66,38,0,8.08,PE,1594492681,A.h Pueblo Nuevo Acari
1,24,24,Pidhorodne,48.58,35.11,71.60,53,0,6.71,UA,1594492690,Dnipro
2,28,28,Caravelas,-17.71,-39.25,76.05,70,0,5.91,BR,1594492692,Caravelas
3,161,161,Antsohihy,-14.88,47.99,70.32,73,0,4.41,MG,1594492758,Antsohihy
4,180,180,Vila Velha,-20.33,-40.29,78.01,61,0,9.17,BR,1594492567,Vila Velha
5,209,209,Shaunavon,49.65,-108.42,75.22,36,0,6.80,CA,1594492783,Shaunavon
6,250,250,Oruzgan,32.83,66.00,70.05,28,0,5.84,AF,1594492804,Chora
7,251,251,BeyÅŸehir,37.68,31.72,70.02,39,0,4.83,TR,1594492804,BeyÅŸehir
8,328,328,Arrondissement d'Ajaccio,42.00,8.92,77.00,78,0,5.82,FR,1594492915,Bastelica
9,356,356,Angoche,-16.23,39.91,72.90,75,0,7.54,MZ,1594492929,Angoche Island
10,407,407,AlpinÃ³polis,-20.86,-46.39,74.95,44,0,5.59,BR,1594492957,AlpinÃ³polis
11,474,474,Uglovoye,44.82,33.60,71.31,61,0,8.03,UA,1594492989,Sevastopol
12,493,493,Vallenar,-28.57,-70.76,75.88,22,0,6.22,CL,1594492999,Vallenar
13,503,503,Atbasar,51.80,68.33,72.28,75,0,4.68,KZ,1594492857,Atbasar
14,525,525,Mirabela,-16.26,-44.16,79.09,31,0,7.34,BR,1594493014,Mirabela
15,549,549,Payo,-3.75,103.64,71.80,95,0,2.04,ID,1594493025,Lahat Regency
16,553,553,Kamina,-8.74,24.99,70.93,46,0,2.71,CD,1594493027,Kamina

In [13]:
hotel_df

['A.h Pueblo Nuevo Acari',
 'Dnipro',
 'Caravelas',
 'Antsohihy',
 'Vila Velha',
 'Shaunavon',
 'Chora',
 'BeyÅŸehir',
 'Bastelica',
 'Angoche Island',
 'AlpinÃ³polis',
 'Sevastopol',
 'Vallenar',
 'Atbasar',
 'Mirabela',
 'Lahat Regency',
 'Kamina']

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in weatherConditions.iterrows()]
loc = weatherConditions[["Lat", "Lng"]]

In [16]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(loc)

# Display figure
h_map.add_layer(markers)
h_map

Figure(layout=FigureLayout(height='420px'))